"""empty message

Revision ID: 135772a40515
Revises: 40570454aaf0
Create Date: 2022-06-03 22:02:56.943475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135772a40515'
down_revision = '40570454aaf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('available_from', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('available_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'available_to')
    op.drop_column('Venue', 'available_from')
    # ### end Alembic commands ###
