"""empty message

Revision ID: 1b1c21356ab9
Revises: 135772a40515
Create Date: 2022-06-03 22:22:28.447508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1c21356ab9'
down_revision = '135772a40515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_from', sa.DateTime(), nullable=True))
    op.add_column('Artist', sa.Column('available_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_to')
    op.drop_column('Artist', 'available_from')
    # ### end Alembic commands ###
