"""empty message

Revision ID: 40570454aaf0
Revises: b47cc54cad2d
Create Date: 2022-06-03 15:29:25.937984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40570454aaf0'
down_revision = 'b47cc54cad2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'seeking_artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_artist', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
