"""empty message

Revision ID: 71dbdb7dc0f3
Revises: aaf9357cc740
Create Date: 2022-06-04 21:25:56.642043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dbdb7dc0f3'
down_revision = 'aaf9357cc740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
