"""empty message

Revision ID: 836be06666ee
Revises: 287bef87afe3
Create Date: 2022-06-04 21:34:32.350518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836be06666ee'
down_revision = '287bef87afe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('available_from', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('available_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'available_to')
    op.drop_column('Venue', 'available_from')
    # ### end Alembic commands ###
